# Generated by Django 5.0 on 2023-12-08 09:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0002_alter_books_upload_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='author',
            field=models.CharField(default=datetime.datetime(2023, 12, 8, 9, 48, 44, 539571, tzinfo=datetime.timezone.utc), max_length=25),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='books',
            name='genre',
            field=models.CharField(choices=[('Poem', 'Poem'), ('Story', 'Story'), ('Artical', 'Artical')], default='Misc', max_length=20),
        ),
        migrations.AlterField(
            model_name='books',
            name='upload_date',
            field=models.DateField(blank=True, default=datetime.datetime(2023, 12, 8, 9, 48, 30, 448353, tzinfo=datetime.timezone.utc)),
        ),
    ]
