# Generated by Django 4.2.7 on 2023-12-12 06:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0005_alter_books_genre_alter_books_upload_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='genre',
            field=models.CharField(choices=[('Poem', 'Poem'), ('Story', 'Story'), ('Article', 'Article'), ('Report', 'Report'), ('Others', 'Others')], max_length=20),
        ),
        migrations.AlterField(
            model_name='books',
            name='upload_date',
            field=models.DateField(blank=True, default=datetime.datetime(2023, 12, 12, 6, 57, 31, 754193, tzinfo=datetime.timezone.utc)),
        ),
    ]
