# Generated by Django 4.2.7 on 2024-01-27 05:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0006_alter_books_genre_alter_books_upload_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=25)),
                ('email', models.EmailField(max_length=30, null=True)),
                ('address', models.CharField(max_length=20, null=True)),
                ('password', models.CharField(max_length=20, null=True)),
                ('confirm_password', models.CharField(max_length=20, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='books',
            name='upload_date',
            field=models.DateField(blank=True, default=datetime.datetime(2024, 1, 27, 5, 49, 13, 735623, tzinfo=datetime.timezone.utc)),
        ),
    ]
